// src/components/ChatWindow.tsx
import React, { useEffect, useRef } from 'react';
import { ChatMessage } from '../types/chat';

interface ChatWindowProps {
    messages: ChatMessage[];
}

const ChatWindow: React.FC<ChatWindowProps> = ({ messages }) => {
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    return (
        <div className="flex-1 overflow-y-auto p-4 bg-gray-50">
            <div className="max-w-3xl mx-auto space-y-4">
                {messages.map((message, index) => (
                    <div
                        key={index}
                        className={`flex ${message.username === 'user' ? 'justify-end' : 'justify-start'}`}
                    >
                        <div
                            className={`max-w-[80%] rounded-lg p-3 ${
                                message.username === 'user'
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-white border border-gray-200'
                            }`}
                        >
                            <p className="text-sm">{message.message}</p>
                        </div>
                    </div>
                ))}
                <div ref={messagesEndRef} />
            </div>
        </div>
    );
};

export default ChatWindow;

// src/components/ChatWindow.vue
<template>
  <div class="flex-1 overflow-y-auto p-4 bg-gray-50">
    <div class="max-w-3xl mx-auto space-y-4">
      <div
        v-for="(message, index) in messages"
        :key="index"
        :class="['flex', message.username === 'user' ? 'justify-end' : 'justify-start']"
      >
        <div
          :class="[
            'max-w-[80%] rounded-lg p-3',
            message.username === 'user'
              ? 'bg-blue-600 text-white'
              : 'bg-white border border-gray-200'
          ]"
        >
          <p class="text-sm">{{ message.message }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { ChatMessage } from '@/types/chat';

@Component
export default class ChatWindow extends Vue {
  @Prop({ required: true }) readonly messages!: ChatMessage[];
}
</script>
